# Generated by Django 5.0.4 on 2024-04-15 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20240411_1939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='menuname',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='menunameitem',
            options={'ordering': ['pk', 'level']},
        ),
        migrations.AddField(
            model_name='menunameitem',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_name_items_parent', to='menu.menuitem'),
        ),
        migrations.AlterField(
            model_name='menuname',
            name='items',
            field=models.ManyToManyField(related_name='menu', through='menu.MenuNameItem', to='menu.menuitem'),
        ),
        migrations.AlterField(
            model_name='menunameitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_name_items_item', to='menu.menuitem'),
        ),
    ]
