# Generated by Django 5.0.4 on 2024-04-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menuitem_options_alter_menuname_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menunameitem',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
