# Generated by Django 5.0.4 on 2024-04-22 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menunameitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menunameitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_name_items_parent', to='menu.menuitem'),
        ),
    ]
