# Generated by Django 5.0.4 on 2024-04-22 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_menunameitem_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menunameitem',
            options={'ordering': ['menu', 'order']},
        ),
    ]
